import type { TravelPackage, GlobalParams, ScenarioConfig, User, Testimonial } from "@/types"

export const MOCK_USER: User = {
  uid: "admin-001",
  email: "admin@siviajes.com",
  name: "Admin SI VIAJES",
  role: "admin",
}

export const DEFAULT_PARAMS: GlobalParams = {
  booking: {
    baseCharge: 0.1,
    paymentMethods: [
      { name: "Efectivo", rate: 0 },
      { name: "Tarjeta", rate: 0.03 },
      { name: "Transferencia", rate: 0.01 },
    ],
    earlyBirdDiscount: 0.1,
    groupDiscounts: [
      { minTravelers: 4, discount: 0.05 },
      { minTravelers: 10, discount: 0.12 },
    ],
  },
  general: {
    taxRate: 21,
    currencySymbol: "$",
    currencyCode: "ARS",
    contactEmail: "info@siviajes.com",
    contactPhone: "+54 11 3390-0101",
    contactWhatsApp: "5491133900101",
  },
  announcement: {
    enabled: false,
    text: "Reservá con 30 días de anticipación y obtené 10% OFF · 3 cuotas sin interés",
  },
}

export const SCENARIOS: Record<string, ScenarioConfig> = {
  base: { label: "Base", demandMultiplier: 1, priceMultiplier: 1 },
  optimistic: { label: "Optimista", demandMultiplier: 1.2, priceMultiplier: 1.1 },
  pessimistic: { label: "Pesimista", demandMultiplier: 0.8, priceMultiplier: 0.9 },
}

export const MOCK_PACKAGES: TravelPackage[] = [
  {
    id: "pkg1",
    name: "Caribe Mexicano",
    destination: "Caribe",
    country: "México",
    duration: "7 días",
    accommodation: "Premium",
    price: 385000,
    previousPrice: 420000,
    description: "Playas paradisíacas de Cancún y Riviera Maya. Disfrutá del Caribe mexicano con resorts todo incluido, aguas turquesas y arena blanca.",
    includes: ["Vuelos ida y vuelta", "Hotel 5 estrellas", "Todo incluido", "Seguro de viaje", "Excursión a Chichén Itzá", "Traslados"],
    excludes: ["Comidas fuera del hotel", "Propinas", "Gastos personales", "Tasa de aeropuerto"],
    itinerary: [
      { day: 1, title: "Llegada a Cancún", description: "Recepción en aeropuerto y traslado al resort", activities: ["Check-in", "Cena de bienvenida"], meals: ["Cena"], accommodation: "Resort 5*" },
      { day: 2, title: "Riviera Maya", description: "Día de playa y snorkel en cenotes", activities: ["Snorkel", "Cenote Ik Kil"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Resort 5*" },
      { day: 3, title: "Chichén Itzá", description: "Excursión a la maravilla del mundo maya", activities: ["Tour guiado", "Fotografía"], meals: ["Desayuno", "Almuerzo"], accommodation: "Resort 5*" },
    ],
    imageUrl: "https://images.pexels.com/photos/7589674/pexels-photo-7589674.jpeg?w=800&q=80",
    images: [
      "https://images.pexels.com/photos/14212425/pexels-photo-14212425.jpeg?w=800&q=80",
      "https://images.pexels.com/photos/13688695/pexels-photo-13688695.jpeg?w=800&q=80",
      "https://images.pexels.com/photos/17244361/pexels-photo-17244361.jpeg?w=800&q=80",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?w=800&q=80",
      "https://images.pexels.com/photos/235734/pexels-photo-235734.jpeg?w=800&q=80",
    ],
    maxCapacity: 30,
    availableSpots: 15,
    tags: ["playa", "caribe", "todo-incluido", "mexico"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg2",
    name: "Maravillas de Perú",
    destination: "Sudamérica",
    country: "Perú",
    duration: "8 días",
    accommodation: "Premium",
    price: 295000,
    previousPrice: 350000,
    description: "Machu Picchu, Cusco y Lima. Descubrí la magia del imperio incaico con guías expertos y alojamiento premium.",
    includes: ["Vuelos", "Hoteles 4*", "Tren a Machu Picchu", "Entradas a sitios arqueológicos", "Guía bilingüe", "Seguro"],
    excludes: ["Comidas no especificadas", "Propinas", "Gastos personales"],
    itinerary: [
      { day: 1, title: "Llegada a Lima", description: "Recepción y city tour por el centro histórico", activities: ["Plaza Mayor", "Catacumbas"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Cusco Imperial", description: "Vuelo a Cusco y aclimatación", activities: ["Sacsayhuamán", "Qenqo"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
      { day: 3, title: "Machu Picchu", description: "Tren a Aguas Calientes y visita guiada a la ciudadela", activities: ["Machu Picchu", "Huayna Picchu opcional"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80",
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
      "https://images.unsplash.com/photo-1509216244219-494322a8b6a4?w=800&q=80",
      "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=800&q=80",
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    ],
    maxCapacity: 20,
    availableSpots: 10,
    tags: ["cultural", "historia", "aventura", "sudamerica"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg3",
    name: "Europa Imperial",
    destination: "Europa",
    country: "Italia/Francia/España",
    duration: "14 días",
    accommodation: "Lujo",
    price: 890000,
    previousPrice: 990000,
    description: "París, Roma, Barcelona. Un recorrido imperial por las capitales más emblemáticas de Europa con alojamiento de lujo.",
    includes: ["Vuelos internacionales", "Hoteles 5*", "Trenes rápidos", "Entradas a museos", "Guía privado", "Seguro premium", "Traslados"],
    excludes: ["Comidas no especificadas", "Propinas", "Gastos personales", "Visas"],
    itinerary: [
      { day: 1, title: "Llegada a París", description: "Recepción y paseo nocturno por la ciudad luz", activities: ["Torre Eiffel iluminada"], meals: ["Cena"], accommodation: "Hotel 5*" },
      { day: 2, title: "París Monumental", description: "Visita al Louvre, Notre Dame y Montmartre", activities: ["Museo del Louvre", "Sacre Coeur"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 5*" },
      { day: 3, title: "Roma Eterna", description: "Tren a Roma y visita al Coliseo", activities: ["Coliseo", "Fontana di Trevi"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Hotel 5*" },
    ],
    imageUrl: "https://images.pexels.com/photos/2082103/pexels-photo-2082103.jpeg",
    images: [
      "https://images.pexels.com/photos/2082103/pexels-photo-2082103.jpeg",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg",
      "https://images.pexels.com/photos/1388030/pexels-photo-1388030.jpeg",
      "https://images.pexels.com/photos/235734/pexels-photo-235734.jpeg",
      "https://images.pexels.com/photos/2404843/pexels-photo-2404843.jpeg",
    ],
    maxCapacity: 25,
    availableSpots: 8,
    tags: ["lujo", "europa", "cultural", "historia"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg4",
    name: "Brasil Tropical",
    destination: "Sudamérica",
    country: "Brasil",
    duration: "7 días",
    accommodation: "Estándar",
    price: 250000,
    previousPrice: 300000,
    description: "Río de Janeiro y Búzios. Playas icónicas, samba, caipirinhas y la energía carioca te esperan.",
    includes: ["Vuelos", "Hotel 3*", "Traslados", "City tour", "Excursión a Búzios", "Seguro"],
    excludes: ["Comidas no incluidas", "Entradas a eventos", "Propinas"],
    itinerary: [
      { day: 1, title: "Llegada a Río", description: "Check-in y tarde en Copacabana", activities: ["Playa de Copacabana"], meals: ["Cena"], accommodation: "Hotel 3*" },
      { day: 2, title: "Río de Janeiro", description: "Cristo Redentor y Pan de Azúcar", activities: ["Cristo Redentor", "Pan de Azúcar"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 3*" },
    ],
    imageUrl: "https://images.pexels.com/photos/169647/pexels-photo-169647.jpeg",
    images: [
      "https://images.pexels.com/photos/169647/pexels-photo-169647.jpeg",
      "https://images.pexels.com/photos/235734/pexels-photo-235734.jpeg",
      "https://images.pexels.com/photos/1955696/pexels-photo-1955696.jpeg",
      "https://images.pexels.com/photos/2404843/pexels-photo-2404843.jpeg",
      "https://images.pexels.com/photos/169647/pexels-photo-169647.jpeg",
    ],
    maxCapacity: 35,
    availableSpots: 22,
    tags: ["playa", "tropical", "sudamerica", "fiesta"],
    featured: false,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg5",
    name: "Patagonia Argentina",
    destination: "Nacional",
    country: "Argentina",
    duration: "10 días",
    accommodation: "Premium",
    price: 340000,
    previousPrice: 390000,
    description: "Glaciar Perito Moreno, Ushuaia y el Fin del Mundo. Naturaleza extrema en la Patagonia argentina.",
    includes: ["Vuelos internos", "Hoteles 4*", "Excursiones", "Guía bilingüe", "Seguro", "Equipo de trekking"],
    excludes: ["Comidas no especificadas", "Equipo personal", "Propinas"],
    itinerary: [
      { day: 1, title: "Llegada a El Calafate", description: "Recepción y traslado al hotel", activities: ["City tour"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Glaciar Perito Moreno", description: "Excursión al glaciar con navegación", activities: ["Trekking", "Navegación"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Hotel 4*" },
      { day: 3, title: "Ushuaia", description: "Vuelo a Ushuaia y navegación por el Canal Beagle", activities: ["Canal Beagle", "Lobos marinos"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg",
    images: [
      "https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg",
      "https://images.pexels.com/photos/3616234/pexels-photo-3616234.jpeg",
      "https://images.pexels.com/photos/235734/pexels-photo-235734.jpeg",
      "https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg",
      "https://images.pexels.com/photos/235734/pexels-photo-235734.jpeg",
    ],
    maxCapacity: 20,
    availableSpots: 12,
    tags: ["aventura", "naturaleza", "trekking", "patagonia"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg6",
    name: "Norte Argentino",
    destination: "Nacional",
    country: "Argentina",
    duration: "6 días",
    accommodation: "Estándar",
    price: 165000,
    previousPrice: 200000,
    description: "Salta, Jujuy, Cafayate. Recorré los paisajes más coloridos del norte argentino con vinos y folclore.",
    includes: ["Vuelos", "Hoteles 3*", "Excursiones", "Guía", "Seguro", "Degustación de vinos"],
    excludes: ["Comidas no incluidas", "Propinas", "Gastos personales"],
    itinerary: [
      { day: 1, title: "Llegada a Salta", description: "Recepción y city tour por la ciudad", activities: ["Plaza 9 de Julio", "Teleférico"], meals: ["Cena"], accommodation: "Hotel 3*" },
      { day: 2, title: "Quebrada de Humahuaca", description: "Recorrido por Purmamarca y Tilcara", activities: ["Cerro de los Siete Colores", "Pucará"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 3*" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800",
    images: [
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800",
      "https://images.unsplash.com/photo-1588418892007-4073571d27ab?w=800",
      "https://images.unsplash.com/photo-1531969179221-3946e6b5a5e7?w=800",
      "https://images.unsplash.com/photo-1519452575417-494b8b2c4ae6?w=800",
      "https://images.unsplash.com/photo-1595053216809-02d35c4c80b7?w=800",
    ],
    maxCapacity: 25,
    availableSpots: 18,
    tags: ["nacional", "cultura", "naturaleza", "vinos"],
    featured: false,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg7",
    name: "Tailandia y Vietnam",
    destination: "Asia",
    country: "Tailandia/Vietnam",
    duration: "15 días",
    accommodation: "Premium",
    price: 580000,
    previousPrice: 650000,
    description: "Bangkok, Hanoi, Halong Bay. Una aventura por el sudeste asiático entre templos dorados y bahías milenarias.",
    includes: ["Vuelos", "Hoteles 4*", "Vuelos internos", "Tours", "Seguro", "Crucero Halong Bay"],
    excludes: ["Visas", "Comidas no incluidas", "Propinas"],
    itinerary: [
      { day: 1, title: "Bangkok", description: "Llegada y city tour por los templos", activities: ["Templo del Amanecer", "Mercado flotante"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Hanoi", description: "Vuelo a Hanoi y exploración del casco antiguo", activities: ["Barrio Francés", "Templo de la Literatura"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
      { day: 3, title: "Halong Bay", description: "Crucero por la bahía con cuevas y kayak", activities: ["Kayak", "Cueva Sung Sot"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Crucero" },
    ],
    imageUrl: "https://images.pexels.com/photos/2070489/pexels-photo-2070489.jpeg",
    images: [
      "https://images.pexels.com/photos/2070489/pexels-photo-2070489.jpeg",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg",
      "https://images.pexels.com/photos/2404843/pexels-photo-2404843.jpeg",
      "https://images.pexels.com/photos/235734/pexels-photo-235734.jpeg",
      "https://images.pexels.com/photos-3228682/pexels-photo-3228682.jpeg",
    ],
    maxCapacity: 18,
    availableSpots: 6,
    tags: ["asia", "aventura", "cultura", "exótico"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg8",
    name: "Nueva York",
    destination: "Norteamérica",
    country: "Estados Unidos",
    duration: "7 días",
    accommodation: "Estándar",
    price: 420000,
    previousPrice: 480000,
    description: "Manhattan, Central Park, Broadway. Viví la energía de la Gran Manzana con los imprescindibles de NYC.",
    includes: ["Vuelos", "Hotel 3*", "Traslados", "Tour NYC", "Seguro", "Entrada a mirador"],
    excludes: ["Comidas", "Compras", "Propinas", "Entradas a shows"],
    itinerary: [
      { day: 1, title: "Llegada a Nueva York", description: "Check-in y tarde en Times Square", activities: ["Times Square", "Rockefeller Center"], meals: [], accommodation: "Hotel 3*" },
      { day: 2, title: "Manhattan", description: "Central Park, Quinta Avenida y Estatua de la Libertad", activities: ["Central Park", "Estatua de la Libertad"], meals: ["Desayuno"], accommodation: "Hotel 3*" },
      { day: 3, title: "Brooklyn y cultura", description: "Puente de Brooklyn y museos", activities: ["Brooklyn Bridge", "MET"], meals: ["Desayuno"], accommodation: "Hotel 3*" },
    ],
imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
      "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80",
      "https://images.unsplash.com/photo-1506971845552-97b4456d3c88?w=800&q=80",
      "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80",
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    ],
    maxCapacity: 30,
    availableSpots: 14,
    tags: ["ciudad", "compras", "cultura", "norteamerica"],
    featured: false,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg9",
    name: "Italia Clásica",
    destination: "Europa",
    country: "Italia",
    duration: "10 días",
    accommodation: "Premium",
    price: 520000,
    previousPrice: 580000,
    description: "Roma, Florencia y Venezia. Viví la historia, el arte y la gastronomía italiana en un recorrido unforgettable por las ciudades más emblemáticas.",
    includes: ["Vuelos internacionales", "Hoteles 4*", "Trenes regionales", "Entradas a museos", "Guía bilingüe", "Seguro", "Traslados"],
    excludes: ["Comidas no especificadas", "Propinas", "Gastos personales", "Visas"],
    itinerary: [
      { day: 1, title: "Llegada a Roma", description: "Recepción y paseo por el centro histórico", activities: ["Plaza de España", "Fontana di Trevi"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Roma Imperial", description: "Visita al Coliseo y Foro Romano", activities: ["Coliseo", "Foro Romano", "Palatino"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
      { day: 3, title: "Vaticano", description: "Museos Vaticanos y Capilla Sixtina", activities: ["Museos Vaticanos", "San Pedro"], meals: ["Desayuno"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80",
      "https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&q=80",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80",
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
      "https://images.unsplash.com/photo-1499678329028-101435549a4e?w=800&q=80",
    ],
    maxCapacity: 25,
    availableSpots: 12,
    tags: ["europa", "arte", "historia", "gastronomia"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-10",
  },
  {
    id: "pkg10",
    name: "España Vibrante",
    destination: "Europa",
    country: "España",
    duration: "9 días",
    accommodation: "Premium",
    price: 480000,
    previousPrice: 540000,
    description: "Madrid, Barcelona y Sevilla. Descubrí la rica cultura española, sus monumentos históricos y la gastronomía local.",
    includes: ["Vuelos internacionales", "Hoteles 4*", "Tren AVE", "Entradas a monumentos", "Guía bilingüe", "Seguro", "Traslados"],
    excludes: ["Comidas no especificadas", "Propinas", "Gastos personales", "Visas"],
    itinerary: [
      { day: 1, title: "Llegada a Madrid", description: "City tour por el centro histórico", activities: ["Plaza Mayor", "Puerta del Sol"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Madrid Real", description: "Visita al Palacio Real y Prado", activities: ["Palacio Real", "Museo del Prado"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
      { day: 3, title: "Barcelona", description: "Tren a Barcelona y paseo por La Rambla", activities: ["La Rambla", "Barri Gòtic"], meals: ["Desayuno"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80",
      "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
      "https://images.unsplash.com/photo-1504019347908-b45f9b0b8dd5?w=800&q=80",
      "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80",
      "https://images.unsplash.com/photo-1543785734-4b6e564642f8?w=800&q=80",
    ],
    maxCapacity: 28,
    availableSpots: 15,
    tags: ["europa", "cultura", "gastronomia", "monumentos"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-10",
  },
  {
    id: "pkg11",
    name: "Francia Encantadora",
    destination: "Europa",
    country: "Francia",
    duration: "8 días",
    accommodation: "Premium",
    price: 550000,
    previousPrice: 620000,
    description: "París, Versalles y la Riviera Francesa. Viví la elegancia francesa, desde la Torre Eiffel hasta las playas de Niza.",
    includes: ["Vuelos internacionales", "Hoteles 4*", "Tren TGV", "Entradas a monumentos", "Guía bilingüe", "Seguro", "Traslados"],
    excludes: ["Comidas no especificadas", "Propinas", "Gastos personales", "Visas"],
    itinerary: [
      { day: 1, title: "Llegada a París", description: "Paseo por los Campos Elíseos", activities: ["Torre Eiffel", "Campos Elíseos"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "París Monumental", description: "Louvre y Notre Dame", activities: ["Museo del Louvre", "Notre Dame"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
      { day: 3, title: "Versalles", description: "Visita al Palacio Real", activities: ["Palacio de Versalles", "Jardines"], meals: ["Desayuno"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
      "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80",
      "https://images.unsplash.com/photo-1478391679764-b2d8b3cd1e94?w=800&q=80",
      "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=800&q=80",
      "https://images.unsplash.com/photo-1520942702018-0862200e6873?w=800&q=80",
    ],
    maxCapacity: 22,
    availableSpots: 10,
    tags: ["europa", "lujo", "romantico", "historia"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-10",
  },
]

export const TESTIMONIALS: Testimonial[] = [
  { id: "t1", name: "María F.", location: "Buenos Aires", text: "Viajé a Cancún con SI VIAJES y fue espectacular. Todo impecable, desde el vuelo hasta las excursiones.", rating: 5 },
  { id: "t2", name: "Jorge L.", location: "Córdoba", text: "Hicimos el recorrido por Europa con mi esposa. La atención y los hoteles fueron de primer nivel.", rating: 5 },
  { id: "t3", name: "Camila R.", location: "Rosario", text: "Patagonia fue un sueño hecho realidad. El tracking al Perito Moreno es algo que todos deberían vivir.", rating: 5 },
  { id: "t4", name: "Federico G.", location: "Mendoza", text: "Muy buena relación precio-calidad. Ya estoy planeando mi próximo viaje con ellos.", rating: 4 },
  { id: "t5", name: "Sofía M.", location: "La Plata", text: "El paquete a Perú fue increíble. Machu Picchu es maravilloso y los guías súper conocedores.", rating: 5 },
]

export const HOLIDAYS = [
  { date: "2026-01-01", name: "Año Nuevo" },
  { date: "2026-02-16", name: "Carnaval" },
  { date: "2026-03-24", name: "Día de la Memoria" },
  { date: "2026-05-01", name: "Día del Trabajador" },
  { date: "2026-05-25", name: "Revolución de Mayo" },
]
