import type { TravelPackage, GlobalParams, ScenarioConfig, User, Testimonial } from "@/types"

export const MOCK_USER: User = {
  uid: "admin-001",
  email: "admin@turismo.com",
  name: "Admin",
  role: "admin",
}

export const DEFAULT_PARAMS: GlobalParams = {
  booking: {
    baseCharge: 0.1,
    paymentMethods: [
      { name: "Efectivo", rate: 0 },
      { name: "Tarjeta", rate: 0.03 },
      { name: "Transferencia", rate: 0.01 },
    ],
    earlyBirdDiscount: 0.1,
    groupDiscounts: [
      { minTravelers: 4, discount: 0.05 },
      { minTravelers: 10, discount: 0.12 },
    ],
  },
  general: {
    taxRate: 21,
    currencySymbol: "$",
    currencyCode: "ARS",
    contactEmail: "info@turismo.com",
    contactPhone: "+54 11 2261-8116",
    contactWhatsApp: "5491122618116",
  },
  announcement: {
    enabled: true,
    text: "Reservá con 30 días de anticipación y obtené 10% OFF · 3 cuotas sin interés",
  },
}

export const SCENARIOS: Record<string, ScenarioConfig> = {
  base: { label: "Base", demandMultiplier: 1, priceMultiplier: 1 },
  optimistic: { label: "Optimista", demandMultiplier: 1.2, priceMultiplier: 1.1 },
  pessimistic: { label: "Pesimista", demandMultiplier: 0.8, priceMultiplier: 0.9 },
}

export const MOCK_PACKAGES: TravelPackage[] = [
  {
    id: "pkg1",
    name: "Caribe de Ensueño",
    destination: "Caribe",
    country: "República Dominicana",
    duration: "7 días",
    accommodation: "Premium",
    price: 450000,
    previousPrice: 520000,
    description: "Disfrutá del Caribe con playas de arena blanca, aguas cristalinas y resorts todo incluido. Incluye vuelos, traslados y excursiones.",
    includes: ["Vuelos ida y vuelta", "Hotel 5 estrellas", "Todo incluido", "Seguro de viaje", "Excursión a Isla Saona"],
    excludes: ["Comidas fuera del hotel", "Propinas", "Gastos personales"],
    itinerary: [
      { day: 1, title: "Llegada a Punta Cana", description: "Recepción en aeropuerto y traslado al resort", activities: ["Check-in", "Cena de bienvenida"], meals: ["Cena"], accommodation: "Resort 5*" },
      { day: 2, title: "Día de Playa", description: "Día libre para disfrutar de las instalaciones", activities: ["Snorkel", "Kayak"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Resort 5*" },
    ],
    imageUrl: "https://placehold.co/600x800/0ea5e9/ffffff?text=Caribe",
    images: [],
    maxCapacity: 30,
    availableSpots: 15,
    tags: ["playa", "caribe", "todo-incluido"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg2",
    name: "Aventura Patagónica",
    destination: "Sudamérica",
    country: "Argentina",
    duration: "10 días",
    accommodation: "Estándar",
    price: 320000,
    previousPrice: 380000,
    description: "Explorá la Patagonia argentina con glaciares, lagos y montañas. Trekking, navegación y avistaje de fauna.",
    includes: ["Vuelos internos", "Hoteles 3*", "Excursiones", "Guía bilingüe", "Equipo de trekking"],
    excludes: ["Comidas no especificadas", "Equipo personal", "Propinas"],
    itinerary: [
      { day: 1, title: "Llegada a El Calafate", description: "Recepción y traslado al hotel", activities: ["City tour"], meals: ["Cena"], accommodation: "Hotel 3*" },
      { day: 2, title: "Glaciar Perito Moreno", description: "Excursión al glaciar con navegación", activities: ["Trekking", "Navegación"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Hotel 3*" },
    ],
    imageUrl: "https://placehold.co/600x800/10b981/ffffff?text=Patagonia",
    images: [],
    maxCapacity: 20,
    availableSpots: 12,
    tags: ["aventura", "naturaleza", "trekking"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg3",
    name: "Europa Clásica",
    destination: "Europa",
    country: "Italia",
    duration: "14 días",
    accommodation: "Premium",
    price: 680000,
    previousPrice: 780000,
    description: "Recorré las ciudades más emblemáticas de Italia: Roma, Florencia, Venecia y Milán. Cultura, historia y gastronomía.",
    includes: ["Vuelos internacionales", "Hoteles 4*", "Trenes rápidos", "Entradas a museos", "Seguro de viaje"],
    excludes: ["Comidas no especificadas", "Propinas", "Gastos personales"],
    itinerary: [
      { day: 1, title: "Llegada a Roma", description: "Recepción y traslado al hotel", activities: ["Paseo nocturno"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Roma Imperial", description: "Visita al Coliseo, Foro Romano y Fontana di Trevi", activities: ["Tour guiado"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://placehold.co/600x800/ec4899/ffffff?text=Europa",
    images: [],
    maxCapacity: 25,
    availableSpots: 8,
    tags: ["cultural", "europa", "historia"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg4",
    name: "Miami & Sol",
    destination: "Norteamérica",
    country: "Estados Unidos",
    duration: "7 días",
    accommodation: "Estándar",
    price: 380000,
    previousPrice: 420000,
    description: "Viví la energía de Miami con sus playas, compras y vida nocturna. Incluye visita a los Everglades.",
    includes: ["Vuelos", "Hotel 3*", "Traslados", "Tour Everglades", "Seguro"],
    excludes: ["Comidas", "Compras", "Propinas"],
    itinerary: [
      { day: 1, title: "Llegada a Miami", description: "Check-in y tarde libre en South Beach", activities: ["Playa"], meals: [], accommodation: "Hotel 3*" },
      { day: 2, title: "Everglades", description: "Excursión a los Everglades con paseo en airboat", activities: ["Airboat", "Avistaje de fauna"], meals: ["Desayuno"], accommodation: "Hotel 3*" },
    ],
    imageUrl: "https://placehold.co/600x800/f59e0b/ffffff?text=Miami",
    images: [],
    maxCapacity: 35,
    availableSpots: 22,
    tags: ["playa", "compras", "ciudad"],
    featured: false,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg5",
    name: "Tailandia Mágica",
    destination: "Asia",
    country: "Tailandia",
    duration: "14 días",
    accommodation: "Premium",
    price: 520000,
    previousPrice: 600000,
    description: "Descubrí los templos dorados, playas paradisíacas y la gastronomía tailandesa. De Bangkok a Phuket.",
    includes: ["Vuelos", "Hoteles 4*", "Vuelos internos", "Tours", "Seguro"],
    excludes: ["Visas", "Comidas no incluidas", "Propinas"],
    itinerary: [
      { day: 1, title: "Bangkok", description: "Llegada y city tour por los templos", activities: ["Templo del Amanecer", "Mercado flotante"], meals: ["Cena"], accommodation: "Hotel 4*" },
      { day: 2, title: "Ayutthaya", description: "Excursión a la antigua capital", activities: ["Templos históricos"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://placehold.co/600x800/7c5cfc/ffffff?text=Tailandia",
    images: [],
    maxCapacity: 20,
    availableSpots: 5,
    tags: ["asia", "cultura", "playa", "exótico"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg6",
    name: "Bariloche Romántico",
    destination: "Nacional",
    country: "Argentina",
    duration: "5 días",
    accommodation: "Premium",
    price: 180000,
    previousPrice: 220000,
    description: "Escapada romántica a Bariloche con chocolate, lagos y montañas. Incluye cena especial.",
    includes: ["Vuelos", "Hotel 4*", "Circuito chico", "Cena romántica", "Seguro"],
    excludes: ["Comidas extras", "Excursiones opcionales"],
    itinerary: [
      { day: 1, title: "Llegada a Bariloche", description: "Recepción y acreditación", activities: ["Paseo por el centro"], meals: ["Cena romántica"], accommodation: "Hotel 4*" },
      { day: 2, title: "Circuito Chico", description: "Recorrido por los lagos y cerros", activities: ["Cerro Campanario", "Puerto Pañuelo"], meals: ["Desayuno", "Almuerzo"], accommodation: "Hotel 4*" },
    ],
    imageUrl: "https://placehold.co/600x800/06b6d4/ffffff?text=Bariloche",
    images: [],
    maxCapacity: 15,
    availableSpots: 7,
    tags: ["romántico", "montaña", "nacional"],
    featured: false,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg7",
    name: "Safari en Kenia",
    destination: "África",
    country: "Kenia",
    duration: "10 días",
    accommodation: "Lujo",
    price: 850000,
    previousPrice: 950000,
    description: "Safari de lujo por las reservas de Kenia. Avistaje de los Cinco Grandes en Masai Mara.",
    includes: ["Vuelos", "Lodges de lujo", "Safaris 4x4", "Guía especializado", "Seguro"],
    excludes: ["Visas", "Vacunas", "Propinas"],
    itinerary: [
      { day: 1, title: "Nairobi", description: "Llegada y descanso", activities: ["Check-in lodge"], meals: ["Cena"], accommodation: "Lodge 5*" },
      { day: 2, title: "Masai Mara", description: "Safari completo en la reserva", activities: ["Avistaje de fauna"], meals: ["Desayuno", "Almuerzo", "Cena"], accommodation: "Lodge 5*" },
    ],
    imageUrl: "https://placehold.co/600x800/10b981/ffffff?text=Safari",
    images: [],
    maxCapacity: 12,
    availableSpots: 4,
    tags: ["aventura", "lujo", "naturaleza", "fauna"],
    featured: true,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "pkg8",
    name: "Tokio Experience",
    destination: "Asia",
    country: "Japón",
    duration: "10 días",
    accommodation: "Estándar",
    price: 580000,
    previousPrice: 650000,
    description: "Sumergite en la cultura japonesa: Tokio, Kioto y Osaka. Tecnología, templos y gastronomía única.",
    includes: ["Vuelos", "Hoteles 3*", "Japan Rail Pass", "Tours guiados", "Seguro"],
    excludes: ["Visas", "Comidas no incluidas"],
    itinerary: [
      { day: 1, title: "Tokio", description: "Llegada y exploración de Shibuya", activities: ["Shibuya Crossing", "Barrio de Harajuku"], meals: ["Cena"], accommodation: "Hotel 3*" },
      { day: 2, title: "Kioto", description: "Tren bala a Kioto, visita a templos", activities: ["Templo Kinkaku-ji", "Bamboo Grove"], meals: ["Desayuno", "Almuerzo"], accommodation: "Ryokan tradicional" },
    ],
    imageUrl: "https://placehold.co/600x800/ec4899/ffffff?text=Tokio",
    images: [],
    maxCapacity: 18,
    availableSpots: 10,
    tags: ["asia", "cultura", "tecnología", "ciudad"],
    featured: false,
    status: "active",
    createdAt: "2026-01-01",
    updatedAt: "2026-05-01",
  },
]

export const TESTIMONIALS: Testimonial[] = [
  { id: "t1", name: "Ana G.", location: "Buenos Aires", text: "El viaje a Europa fue increíble. Superó todas mis expectativas.", rating: 5 },
  { id: "t2", name: "Carlos M.", location: "Córdoba", text: "La organización impecable. Volvería a viajar con ellos sin dudar.", rating: 5 },
  { id: "t3", name: "Lucía P.", location: "Rosario", text: "El safari en Kenia fue la experiencia más increíble de mi vida.", rating: 5 },
  { id: "t4", name: "Martín R.", location: "Mendoza", text: "Muy buena atención y los precios son competitivos. Recomendado.", rating: 4 },
  { id: "t5", name: "Valentina L.", location: "Neuquén", text: "Tailandia superó todas mis expectativas. Guías excelentes.", rating: 5 },
]

export const HOLIDAYS = [
  { date: "2026-01-01", name: "Año Nuevo" },
  { date: "2026-02-16", name: "Carnaval" },
  { date: "2026-03-24", name: "Día de la Memoria" },
  { date: "2026-05-01", name: "Día del Trabajador" },
  { date: "2026-05-25", name: "Revolución de Mayo" },
]
