services:
  - type: web
    name: turismo
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyC4h_r_HAvtzA1DzmDrjQhKQc4GMMC7rC0
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: turismo-cee7d.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: turismo-cee7d
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: turismo-cee7d.firebasestorage.app
      - key: VITE_FIREBASE_SENDER_ID
        value: "371944026595"
      - key: VITE_FIREBASE_APP_ID
        value: 1:371944026595:web:2044d794e25b372bfb70d6
      - key: VITE_FIREBASE_MEASUREMENT_ID
        value: G-ZNBXMKMLGY
